go get -v github.com/asaskevich/govalidator
go get -v github.com/clbanning/mxj
go get -v github.com/go-sql-driver/mysql
go get -v github.com/go-xorm/builder
go get -v github.com/go-xorm/xorm
go get -v github.com/gorilla/mux
go get -v github.com/gorilla/websocket
go get -v github.com/graphql-go/graphql
go get -v github.com/graphql-go/graphql/language/ast
go get -v github.com/jpfielding/gorets/cmds/common
go get -v github.com/jpfielding/gorets/rets
go get -v github.com/lib/pq
go get -v github.com/mattn/go-sqlite3
go get -v gopkg.in/mgo.v2/bson